name: EIITECHFEST2020 
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - pip
  - pip:
      - qiskit
      - qiskit-aqua
      - dimod
      - dwave-ocean-sdk
  - jupyter
  - matplotlib
  - sympy
